development:
  adapter: postgresql
  encoding: unicode
  database: gustavoguichard_development
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: gustavoguichard_test
  min_messages: WARNING
  host: localhost