# development:
#   adapter: sqlite3
#   database: db/development.sqlite3
#   pool: 5
#   timeout: 5000

# test:
#   adapter: sqlite3
#   database: db/test.sqlite3
#   pool: 5
#   timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: gustavoguichard_development
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: gustavoguichard_test
  min_messages: WARNING
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: gustavog_portfolio
  pool: 5
  username: gustavog_port
  password: portugaL2013
  host: localhost